### ISSUE TITLE
Startup and Crashing on Silicon Mac (M3) and Bridge

### ISSUE THREAD

**Issue by rfhandel** [adobe-dmeservices/custom-metadata#42] opened 2024-07-17 20:15 UTC
**Description**
Panel does not save properly and any attempt to edit a tab or create a new one results in instability and results in Bridge not restarting until Custom Metadata is uninstalled.

**Steps to reproduce**
**_Panel Behavior_**
Upon installation, the panel appears to work fine upon opening; the panel loads after selecting an item, but 
1. when filling out the pre-loaded keywords and 
2. saving them for the Pet Shop Metadata, 
3. once the drop-down choices are picked and the Name is entered, 
4. "Save Changes" only keeps the Name and Breed when switching to another item and switching back. (i.e. Pet Type, Gender, and Arrival Date are all cleared). 
5. Bridge can close and open without problems at this point.

**_Preferences Behavior_**
1. However, once preferences are opened and 
2. View Editor or Tab management are edited, 
3. the panel becomes unstable 
4. the edits to a field are saved (e.g. Pet Type options)
5. but the Preferences cannot be opened again to adjust.  
6. Then, upon closing Bridge and reopening, Bridge fails to open.

**Workarounds**
None so far that make this a workable solution for use as a metadata solution

**Expected behavior**
Everything should just open and work as demonstrated in the demos and overviews.

**Screenshots**
![Screenshot 2024-07-17 at 3 33 21 PM](https://github.com/user-attachments/assets/d4a7f630-63d1-4a56-bb5e-65dd9db37049)
![Screenshot 2024-07-17 at 3 44 55 PM](https://github.com/user-attachments/assets/83a014e8-26e6-4706-a881-10ec9e56d285)
![Screenshot 2024-07-17 at 3 47 48 PM](https://github.com/user-attachments/assets/f65cf00d-abb9-43db-83c6-5ca0e8ac4174)
<img width="511" alt="Screenshot 2024-07-17 at 3 53 30 PM" src="https://github.com/user-attachments/assets/f408f606-324c-46d8-8418-60d9527ad68f">
<img width="980" alt="Screenshot 2024-07-17 at 3 56 48 PM" src="https://github.com/user-attachments/assets/12985a27-2710-4369-b9d8-243eea2eadaf">

**XMP Metadata**
Attach raw XMP metadata (if applicable).

**Metadata View JSON**
[Test4Crash.json](https://github.com/user-attachments/files/16274231/Test4Crash.json)

**Environment**
* OS type and version: Sonoma 14.5
* Extension version: 2.0.2
* Any other relevant info: After ascertaining that this extension perfectly fits my needs, I proceeded to install version 2.0.2 from Adobe Exchange. I have not experiemented with Photoshop or Illustrator and am using version 14.1.1 of Bridge with an Apple M3 Max MacBook Pro with 48 GB of RAM running Sonoma 14.5.

**Comment by rfhandel** [comment] 2024-07-17 21:00
Follow up: I just checked this on an M1 Mac Mini and had the same problem.  However, I did have a brief view of the problem with a GPU warning, which I have attached here.

![Screenshot 2024-07-17 at 4 52 48 PM](https://github.com/user-attachments/assets/a744a775-6504-4323-9ecb-21012974fb32)

**Comment by rfhandel** [comment] 2024-07-18 19:29
Reinstalled and attempted to use in Photoshop under Rosetta and after editing the default Tab, I could no longer access the extension.  Was given this message:

<img width="740" alt="Screenshot 2024-07-18 at 3 20 03 PM" src="https://github.com/user-attachments/assets/f2868753-e9bc-443a-993b-4ba398fa8a8d">

**Comment by jameslockman** [comment] 2024-07-18 19:47
Hello!
We are unable to reproduce here, with an M2 Macbook Pro running the same version of MacOS, but with 32GB of RAM.

Our panel does not use the GPU, and our extension signing is managed by Marketplace. Can you please:

- Uninstall the extension
- Get [Anastasiy's Extension Manager](https://install.anastasiy.com)
- Download the extension (current version is 2.0.1) from the[ Releases section](https://github.com/adobe-dmeservices/custom-metadata/releases)
- Install using Anastasiy's Extension manager

**Comment by rfhandel** [comment] 2024-07-20 15:06
Thanks for the speedy response.  Not sure what is the problem, but I even tried on an old MacBook with similar problems, but I used the Extension Manager to install and even though the interface seemed a bit different (more keywords showed up in the panel, but that could just be the file I chose to start), same problem.  When I try to edit the "default" file, I cannot re-edit the file, and once I close Bridge and restart, it crashes.  Would it be useful to paste the entire crash report from Apple?

**Comment by jameslockman** [comment] 2024-09-14 01:03
We've made some adjustments that you can view in the [2.0.2 beta 1 release](https://github.com/adobe-dmeservices/custom-metadata/releases/tag/2.0.2). Please download and see if this works for you!

**Comment by jameslockman** [comment] 2024-11-15 19:00
Closed in https://github.com/adobe-dmeservices/custom-metadata/releases/tag/2.0.2

**Comment by jameslockman** [comment] 2024-11-15 19:00
Closed in https://github.com/adobe-dmeservices/custom-metadata/releases/tag/2.0.2

**Closed** 2024-11-15 19:01 UTC
Labels: bug, In Beta
